[package]
name = "pbp-blinky"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"
uart16550 = "*"
artinchip-hal = { version = "0.0.0", path = "../../../artinchip-hal" }
artinchip-rt = { version = "0.0.0", path = "../../../artinchip-rt" }
