[package]
name = "artinchip-rt"
version = "0.0.0"
edition = "2024"

[dependencies]
artinchip-rt-macros = { version = "0.0.0", path = "macros" }

[features]
d12x = []
d13x = []
d21x = []
g73x = []
m6800 = []
